---
# Synopsis: Suppress Rules for the Management Group Hierarchy template
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: "SuppressNSParameters"
spec:
  rule:
    - Azure.RBAC.LimitMGDelegation
    - Azure.RBAC.LimitOwner
  if:
    source: Template
    withinPath:
      - bicep/templates/managementGroups/
